<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="CCHNPVR_lb_.aspx.cs" Inherits="conns.CCHNPVR_lb_Form"  MasterPageFile="~/Themes/Current/MasterPage.master" %>
<%@ Register  TagPrefix="mdf" Assembly="ASNA.Monarch.WebDspF, Version=12.0.48.0, Culture=neutral, PublicKeyToken=71de708db13b26d3" Namespace="ASNA.Monarch.WebDspF" %>

    <asp:Content ContentPlaceHolderID="HeaderPH" runat="Server" >
        <%-- Migrated on 4/18/2016 at 3:36 PM by ASNA Monarch(R) Wings version 7.0.58.0 --%>
        <%-- Legacy location: library asnaDSRC, file QDDSSRC, member CCHNPVR# --%>

    </asp:Content>

    <asp:Content ID="FileContent1" runat="server" ContentPlaceHolderID="FKeyPH">
        <div id="Div0">
            
            <mdf:ddsfile id="CCHNPVR_lb_Control" runat="server" 
            BannerStyle="Horizontal"
            DisplayErrorMessages="False"
            SrcDdsCcsid="37" 
            PixelPerCharWidth="8" 
            PixelPerCharHeight="24"  />

        </div>
    </asp:Content>


    <asp:Content ID="FileContent2" runat="server" ContentPlaceHolderID="CenPH">
        <div id="Div1">
            
      <%--  CA: PMT for Quotes        Prompt & validate record                              --%>
      <%--  CRTDSPF                                                                         --%>
      <%--  RSTDSP(*YES)                                                                    --%>
      <%--  MEMBER-ID: CCHNPVR#                                                             --%>
      <%--                                                                                  --%>
      <%--  Generated by CA 2E release 2E ( 1547)                                           --%>
      <%--  Function type : Prompt & validate record                                        --%>
      <%--                                                                                  --%>
      <%--  Company       : Conn Credit Corp.                                               --%>
      <%--  System        : Conn Credit Corp.                                               --%>
      <%--  User name     : UJOG                                                            --%>
      <%--  Date          : 01/29/16  Time  : 20:30:32                                      --%>
      <%--  Copyright     : Conn Credit Corp.                                               --%>
      <%-- ================================================================                 --%>
      <%--  Maintenance   :                                                                 --%>
      <%-- ================================================================                 --%>
      <%-- =========================================================================        --%>
          <mdf:DdsRecord id="_lb_RCDDTL1" runat="server" 
            style="position: relative; width: 756px; height: 456px" 
            Alias="#RCDDTL1"
            CssClass="DdsRecord"
            AttnKeys="F3 'Exit.' 03;F12 'Exit.' 12;Help 'Help.' 25;"
            FuncKeys="F4 'Prompt.' 04;F5 'Reset.' 05;F9 'CF09.' 09;F10 'CF10.' 10;"
            SetOfInds="98 99 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 " 
            CommandKeyInd="29" 
            CursorLocation="'ZZCSRW,ZZCSCL' : 04 | 94 | 25"
          >&nbsp;
          <%--  COMMAND KEYS............................................................        --%>
          <%--  SETOFFS.................................................................        --%>
          <%-- .........................................................................        --%>
          <%--  Reposition cursor to where?                                                     --%>
          <%--  User name                                                                       --%>
          <%--  Company name                                                                    --%>
          <%--  *DATE                                                                           --%>
          <%--  Program name                                                                    --%>
          <%--  Job name                                                                        --%>
          <%--  Screen title                                                                    --%>
          <%--  *TIME                                                                           --%>
          <%--  *Program mode                                                                   --%>
          <%--  Selection prompt text                                                           --%>
          <%--  Loan Type                                                                       --%>
          <%--  Nbr: Application                                                                --%>
          <%--  Nbr: Appl Dtl Item                                                              --%>
          <%--  Nbr: Model                                                                      --%>
          <%--  Cde: User Stamp                                                                 --%>
          <%--  PROGRAM                                                                         --%>
          <%--  Dte: Audit Stamp                                                                --%>
          <%--  Tme: Audit Stamp                                                                --%>
          <%--  Code: Contract State                                                            --%>
          <%--  Code: Contract State                                                            --%>
          <%--  Cde: Employee                                                                   --%>
          <%--  Cde: Employee                                                                   --%>
          <%--  Txt: Employee Name                                                              --%>
          <%--  Cde: Payment Method                                                             --%>
          <%--  Cde: Payment Method                                                             --%>
          <%--  Condition: Credit Payments                                                      --%>
          <%--  Nbr: Credit Account.                                                            --%>
          <%--  Nbr: Credit Account.                                                            --%>
          <%--  Principal Balance                                                               --%>
          <%--  Principal Balance                                                               --%>
          <%--  Sts: A/H Insurance                                                              --%>
          <%--  Sts: A/H Insurance                                                              --%>
          <%--  Sts: C/L Insurance                                                              --%>
          <%--  Sts: C/L Insurance                                                              --%>
          <%--  Sts: Prp Insurnace                                                              --%>
          <%--  Sts: Prp Insurnace                                                              --%>
          <%--  Sts: Uem Insurnace                                                              --%>
          <%--  Sts: Uem Insurnace                                                              --%>
          <%--  Vlu: Down Payment                                                               --%>
          <%--  Vlu: Down Payment                                                               --%>
          <%--  xxx                                                                             --%>
          <%--  xxx                                                                             --%>
          <%--  Payments                                                                        --%>
          <%--  Payments                                                                        --%>
          <%--  Payments                                                                        --%>
          <%--  Payment Amount                                                                  --%>
          <%--  Payment Amount                                                                  --%>
          <%--  *CON (Screen constant)                                                          --%>
          <%--  Cde: Product Category                                                           --%>
          <%--  Description: Prod Cat                                                           --%>
          <%--  Nbr: Product Quantity                                                           --%>
          <%--  Vlu: Product                                                                    --%>
          <%--  Vlu: Product Maint.                                                             --%>
          <%--  Vlu: Report Total 01                                                            --%>
          <%--  Cde: Prd Cat (2)                                                                --%>
          <%--  Dsc: Prd Cat (2)                                                                --%>
          <%--  Qty: Product (2)                                                                --%>
          <%--  Vlu: Product (2)                                                                --%>
          <%--  Vlu: Prd SMA (2)                                                                --%>
          <%--  Vlu: Prd Line (2)                                                               --%>
          <%--  Cde: Prd Cat (3)                                                                --%>
          <%--  Dsc: Prd Cat (3)                                                                --%>
          <%--  Qty: Product (3)                                                                --%>
          <%--  Vlu: Product (3)                                                                --%>
          <%--  Vlu: Prd SMA (3)                                                                --%>
          <%--  Vlu: Prd Line (3)                                                               --%>
          <%--  Cde: Prd Cat (4)                                                                --%>
          <%--  Dsc: Prd Cat (4)                                                                --%>
          <%--  Qty: Product (4)                                                                --%>
          <%--  Vlu: Product (4)                                                                --%>
          <%--  Vlu: Prd SMA (4)                                                                --%>
          <%--  Vlu: Prd Line (4)                                                               --%>
          <%-- =========================================================================        --%>
            <mdf:DdsDecField id="_lb_RCDDTL1_ZZCSRW" runat="server" style="position: absolute; left: 1px; top: 0px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              Alias="ZZCSRW" 
              Usage="Hidden" 
 />
            <mdf:DdsDecField id="_lb_RCDDTL1_ZZCSCL" runat="server" style="position: absolute; left: 1px; top: 0px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              Alias="ZZCSCL" 
              Usage="Hidden" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb__lb_USR" runat="server" style="position: absolute; left: 19px; top: 0px; width: 91px"
              CssClass="DdsCharField"
              Length="10" 
              Alias="##USR" 
              Usage="OutputOnly" 
              VirtualRowCol="1,2" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb__lb_CMP" runat="server" style="position: absolute; left: 163px; top: 0px; width: 361px"
              CssClass="DdsCharField"
              Length="40" 
              Alias="##CMP" 
              Usage="OutputOnly" 
              VirtualRowCol="1,18" 
 />
            <mdf:DdsConstant id="DdsConstant17" runat="server" 
              style="position: absolute; left: 577px; top: 3px;"
              Text="*DATE" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb__lb_PGM" runat="server" style="position: absolute; left: 658px; top: 0px; width: 91px"
              CssClass="DdsCharField"
              Length="10" 
              Alias="##PGM" 
              Usage="OutputOnly" 
              VirtualRowCol="1,70" 
              Color="Blue" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb__lb_JOB" runat="server" style="position: absolute; left: 19px; top: 24px; width: 91px"
              CssClass="DdsCharField"
              Length="10" 
              Alias="##JOB" 
              Usage="OutputOnly" 
              VirtualRowCol="2,2" 
 />
            <mdf:DdsConstant id="DdsConstant11" runat="server" 
              style="position: absolute; left: 298px; top: 27px;"
              Text="Calculate Credit Quotes" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb__lb_TME" runat="server" style="position: absolute; left: 577px; top: 24px; width: 73px"
              CssClass="DdsDecField"
              Length="6" 
              Decimals="0" 
              Alias="##TME" 
              Usage="OutputOnly" 
              VirtualRowCol="2,61" 
              EditWord="0 :  :  " 
 />
            <mdf:DdsConstant id="DdsConstant18" runat="server" 
              style="position: absolute; left: 658px; top: 27px;"
              Text="ENTER  " 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DCSCD" runat="server" style="position: absolute; left: 1px; top: 0px; width: 10px"
              CssClass="DdsCharField"
              Length="1" 
              Alias="#DCSCD" 
              Usage="Hidden" 
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1ITNB" runat="server" style="position: absolute; left: 1px; top: 0px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="0" 
              Alias="#1ITNB" 
              Usage="Hidden" 
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1APD_lb_" runat="server" style="position: absolute; left: 1px; top: 0px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              Alias="#1APD#" 
              Usage="Hidden" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_1AXTX" runat="server" style="position: absolute; left: 1px; top: 0px; width: 181px"
              CssClass="DdsCharField"
              Length="20" 
              Alias="#1AXTX" 
              Usage="Hidden" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_1AAVN" runat="server" style="position: absolute; left: 1px; top: 0px; width: 91px"
              CssClass="DdsCharField"
              Length="10" 
              Alias="#1AAVN" 
              Usage="Hidden" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_1ABVN" runat="server" style="position: absolute; left: 1px; top: 0px; width: 91px"
              CssClass="DdsCharField"
              Length="10" 
              Alias="#1ABVN" 
              Usage="Hidden" 
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1AGDT" runat="server" style="position: absolute; left: 1px; top: 0px; width: 64px"
              CssClass="DdsDecField"
              Length="7" 
              Decimals="0" 
              Alias="#1AGDT" 
              Usage="Hidden" 
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1ABTM" runat="server" style="position: absolute; left: 1px; top: 0px; width: 55px"
              CssClass="DdsDecField"
              Length="6" 
              Decimals="0" 
              Alias="#1ABTM" 
              Usage="Hidden" 
 />
            <mdf:DdsConstant id="DdsConstant1" runat="server" 
              style="position: absolute; left: 19px; top: 75px;"
              Text="Contract State of" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DVGCD" runat="server" style="position: absolute; left: 208px; top: 72px; width: 19px"
              CssClass="DdsCharField"
              Length="2" 
              Alias="#DVGCD" 
              Usage="OutputOnly" 
              VirtualRowCol="4,20" 
 />
            <mdf:DdsConstant id="DdsConstant7" runat="server" 
              style="position: absolute; left: 244px; top: 75px;"
              Text="Employee" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DAJCD" runat="server" style="position: absolute; left: 325px; top: 72px; width: 46px"
              CssClass="DdsCharField"
              Length="5" 
              Alias="#DAJCD" 
              Usage="Both" 
              VirtualRowCol="4,33" 
              PositionCursor="31 | !31 & !98 & !99" 
              Color="Red : 31 , Green : !31" 
              TabIndex="1"  />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DA0TX" runat="server" style="position: absolute; left: 379px; top: 72px; width: 271px"
              CssClass="DdsCharField"
              Length="30" 
              Alias="#DA0TX" 
              Usage="OutputOnly" 
              VirtualRowCol="4,39" 
 />
            <mdf:DdsConstant id="DdsConstant2" runat="server" 
              style="position: absolute; left: 28px; top: 123px;"
              Text="Payment Method" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DPQST" runat="server" style="position: absolute; left: 163px; top: 120px; width: 46px"
              CssClass="DdsCharField"
              Length="2" 
              Alias="#DPQST" 
              Usage="Both" 
              VirtualRowCol="6,18" 
              PositionCursor="32" 
              Color="Red : 32 , Green : !32" 
              ValuesStyle="DropdownBoth" 
              Values="' ' 'GE' 'IL' 'I3' 'I6' 'IY' '18' '2Y' '30' '36' 'OF' 'RC' 'R3' 'R6' 'RY' 'RE' '2R' 'RH' '3R' '4R' '5R' '?' " 
              TabIndex="2"  />
            <mdf:DdsConstant id="DdsConstant6" runat="server" 
              style="position: absolute; left: 226px; top: 123px;"
              Text="Credit Account" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DACC_lb_" runat="server" style="position: absolute; left: 361px; top: 120px; width: 109px"
              CssClass="DdsDecField"
              Length="12" 
              Decimals="0" 
              LeftPad="Zeroes" 
              Alias="#DACC#" 
              Usage="Both" 
              VirtualRowCol="6,37" 
              PositionCursor="33" 
              Color="Red : 33 , Green : !33" 
              EditCode="4" 
              TabIndex="3"  />
            <mdf:DdsConstant id="DdsConstant16" runat="server" 
              style="position: absolute; left: 487px; top: 123px;"
              Text="Balance" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DCLVA" runat="server" style="position: absolute; left: 559px; top: 120px; width: 64px"
              CssClass="DdsDecField"
              Length="7" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DCLVA" 
              Usage="Both" 
              VirtualRowCol="6,59" 
              PositionCursor="34" 
              Color="Red : 34 , Green : !34" 
              EditCode="4" 
              TabIndex="4"  />
            <mdf:DdsConstant id="DdsConstant3" runat="server" 
              style="position: absolute; left: 28px; top: 171px;"
              Text="Insurances A/H:" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DLEST" runat="server" style="position: absolute; left: 199px; top: 168px; width: 10px"
              CssClass="DdsCharField"
              Length="1" 
              Alias="#DLEST" 
              Usage="Both" 
              VirtualRowCol="8,19" 
              PositionCursor="35" 
              Color="Red : 35 , Green : !35" 
              TabIndex="5"  />
            <mdf:DdsConstant id="DdsConstant5" runat="server" 
              style="position: absolute; left: 217px; top: 171px;"
              Text="C/L" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DLFST" runat="server" style="position: absolute; left: 253px; top: 168px; width: 10px"
              CssClass="DdsCharField"
              Length="1" 
              Alias="#DLFST" 
              Usage="Both" 
              VirtualRowCol="8,25" 
              PositionCursor="36" 
              Color="Red : 36 , Green : !36" 
              TabIndex="6"  />
            <mdf:DdsConstant id="DdsConstant8" runat="server" 
              style="position: absolute; left: 271px; top: 171px;"
              Text="Prop" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DLGST" runat="server" style="position: absolute; left: 316px; top: 168px; width: 10px"
              CssClass="DdsCharField"
              Length="1" 
              Alias="#DLGST" 
              Usage="Both" 
              VirtualRowCol="8,32" 
              PositionCursor="37" 
              Color="Red : 37 , Green : !37" 
              TabIndex="7"  />
            <mdf:DdsConstant id="DdsConstant12" runat="server" 
              style="position: absolute; left: 334px; top: 171px;"
              Text="U-Emp" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DLHST" runat="server" style="position: absolute; left: 388px; top: 168px; width: 10px"
              CssClass="DdsCharField"
              Length="1" 
              Alias="#DLHST" 
              Usage="Both" 
              VirtualRowCol="8,40" 
              PositionCursor="38" 
              Color="Red : 38 , Green : !38" 
              TabIndex="8"  />
            <mdf:DdsConstant id="DdsConstant15" runat="server" 
              style="position: absolute; left: 424px; top: 171px;"
              Text="Down Payment" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGEVA" runat="server" style="position: absolute; left: 541px; top: 168px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGEVA" 
              Usage="Both" 
              VirtualRowCol="8,57" 
              PositionCursor="39" 
              Color="Red : 39 , Green : !39" 
              EditCode="4" 
              TabIndex="9"  />
            <mdf:DdsConstant id="DdsConstant9" runat="server" 
              style="position: absolute; left: 271px; top: 219px;"
              Text="Total Amount to be Financed" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DPRDV" runat="server" style="position: absolute; left: 523px; top: 216px; width: 109px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              Alias="#DPRDV" 
              Usage="OutputOnly" 
              VirtualRowCol="10,55" 
              EditCode="J" 
 />
            <mdf:DdsConstant id="DdsConstant10" runat="server" 
              style="position: absolute; left: 271px; top: 267px;"
              Text="For" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DDUNB" runat="server" style="position: absolute; left: 307px; top: 264px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              LeftPad="Zeroes" 
              Alias="#DDUNB" 
              Usage="Both" 
              VirtualRowCol="12,31" 
              PositionCursor="40" 
              Color="Red : 40 , Green : !40" 
              EditCode="4" 
              TabIndex="10"  />
            <mdf:DdsConstant id="DdsConstant13" runat="server" 
              style="position: absolute; left: 343px; top: 267px;"
              Text="Months" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsConstant id="DdsConstant14" runat="server" 
              style="position: absolute; left: 406px; top: 267px;"
              Text="With Payment of" 
              VisibleCondition="!( 79 )"
              Color="Blue : !79" 
              CssClass="DdsConstant"
 />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DCJVA" runat="server" style="position: absolute; left: 550px; top: 264px; width: 91px"
              CssClass="DdsDecField"
              Length="7" 
              Decimals="2" 
              Alias="#DCJVA" 
              VisibleCondition="!( 79 )"
              Usage="OutputOnly" 
              VirtualRowCol="12,58" 
              EditCode="J" 
 />
            <mdf:DdsConstant id="DdsConstant4" runat="server" 
              style="position: absolute; left: 37px; top: 315px;"
              Text="Cat - Or Model No.       Qty    Value $    Maint $     Total $" 
              Color="Blue" 
              CssClass="DdsConstant"
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_1PRDC" runat="server" style="position: absolute; left: 37px; top: 360px; width: 28px"
              CssClass="DdsCharField"
              Length="3" 
              Alias="#1PRDC" 
              Usage="Both" 
              VirtualRowCol="16,4" 
              PositionCursor="41" 
              Color="Red : 41 , Green : !41" 
              TabIndex="11"  />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DA6TX" runat="server" style="position: absolute; left: 73px; top: 360px; width: 181px"
              CssClass="DdsCharField"
              Length="20" 
              Alias="#DA6TX" 
              Usage="Both" 
              VirtualRowCol="16,8" 
              PositionCursor="42" 
              Color="Red : 42 , Green : !42" 
              TabIndex="12"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1PRDQ" runat="server" style="position: absolute; left: 289px; top: 360px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              LeftPad="Zeroes" 
              Alias="#1PRDQ" 
              Usage="Both" 
              VirtualRowCol="16,29" 
              PositionCursor="43" 
              Color="Red : 43 , Green : !43" 
              EditCode="4" 
              TabIndex="13"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1GFVA" runat="server" style="position: absolute; left: 325px; top: 360px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#1GFVA" 
              Usage="Both" 
              VirtualRowCol="16,33" 
              PositionCursor="44" 
              Color="Red : 44 , Green : !44" 
              EditCode="4" 
              TabIndex="14"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_1PRDM" runat="server" style="position: absolute; left: 424px; top: 360px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#1PRDM" 
              Usage="Both" 
              VirtualRowCol="16,44" 
              PositionCursor="45" 
              Color="Red : 45 , Green : !45" 
              EditCode="4" 
              TabIndex="15"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DEYVA" runat="server" style="position: absolute; left: 523px; top: 360px; width: 109px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              Alias="#DEYVA" 
              Usage="OutputOnly" 
              VirtualRowCol="16,55" 
              EditCode="J" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DAWCO" runat="server" style="position: absolute; left: 37px; top: 384px; width: 28px"
              CssClass="DdsCharField"
              Length="3" 
              Alias="#DAWCO" 
              Usage="Both" 
              VirtualRowCol="17,4" 
              PositionCursor="46" 
              Color="Red : 46 , Green : !46" 
              TabIndex="16"  />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DUPTX" runat="server" style="position: absolute; left: 73px; top: 384px; width: 181px"
              CssClass="DdsCharField"
              Length="20" 
              Alias="#DUPTX" 
              Usage="Both" 
              VirtualRowCol="17,8" 
              PositionCursor="47" 
              Color="Red : 47 , Green : !47" 
              TabIndex="17"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DI2NB" runat="server" style="position: absolute; left: 289px; top: 384px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              LeftPad="Zeroes" 
              Alias="#DI2NB" 
              Usage="Both" 
              VirtualRowCol="17,29" 
              PositionCursor="48" 
              Color="Red : 48 , Green : !48" 
              EditCode="4" 
              TabIndex="18"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGIVA" runat="server" style="position: absolute; left: 325px; top: 384px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGIVA" 
              Usage="Both" 
              VirtualRowCol="17,33" 
              PositionCursor="49" 
              Color="Red : 49 , Green : !49" 
              EditCode="4" 
              TabIndex="19"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGLVA" runat="server" style="position: absolute; left: 424px; top: 384px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGLVA" 
              Usage="Both" 
              VirtualRowCol="17,44" 
              PositionCursor="50" 
              Color="Red : 50 , Green : !50" 
              EditCode="4" 
              TabIndex="20"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGOVA" runat="server" style="position: absolute; left: 523px; top: 384px; width: 109px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              Alias="#DGOVA" 
              Usage="OutputOnly" 
              VirtualRowCol="17,55" 
              EditCode="J" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DAXCO" runat="server" style="position: absolute; left: 37px; top: 408px; width: 28px"
              CssClass="DdsCharField"
              Length="3" 
              Alias="#DAXCO" 
              Usage="Both" 
              VirtualRowCol="18,4" 
              PositionCursor="51" 
              Color="Red : 51 , Green : !51" 
              TabIndex="21"  />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DUQTX" runat="server" style="position: absolute; left: 73px; top: 408px; width: 181px"
              CssClass="DdsCharField"
              Length="20" 
              Alias="#DUQTX" 
              Usage="Both" 
              VirtualRowCol="18,8" 
              PositionCursor="52" 
              Color="Red : 52 , Green : !52" 
              TabIndex="22"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DI3NB" runat="server" style="position: absolute; left: 289px; top: 408px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              LeftPad="Zeroes" 
              Alias="#DI3NB" 
              Usage="Both" 
              VirtualRowCol="18,29" 
              PositionCursor="53" 
              Color="Red : 53 , Green : !53" 
              EditCode="4" 
              TabIndex="23"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGJVA" runat="server" style="position: absolute; left: 325px; top: 408px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGJVA" 
              Usage="Both" 
              VirtualRowCol="18,33" 
              PositionCursor="54" 
              Color="Red : 54 , Green : !54" 
              EditCode="4" 
              TabIndex="24"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGMVA" runat="server" style="position: absolute; left: 424px; top: 408px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGMVA" 
              Usage="Both" 
              VirtualRowCol="18,44" 
              PositionCursor="55" 
              Color="Red : 55 , Green : !55" 
              EditCode="4" 
              TabIndex="25"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGPVA" runat="server" style="position: absolute; left: 523px; top: 408px; width: 109px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              Alias="#DGPVA" 
              Usage="OutputOnly" 
              VirtualRowCol="18,55" 
              EditCode="J" 
 />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DAYCO" runat="server" style="position: absolute; left: 37px; top: 432px; width: 28px"
              CssClass="DdsCharField"
              Length="3" 
              Alias="#DAYCO" 
              Usage="Both" 
              VirtualRowCol="19,4" 
              PositionCursor="56" 
              Color="Red : 56 , Green : !56" 
              TabIndex="26"  />
            <mdf:DdsCharField id="_lb_RCDDTL1__lb_DURTX" runat="server" style="position: absolute; left: 73px; top: 432px; width: 181px"
              CssClass="DdsCharField"
              Length="20" 
              Alias="#DURTX" 
              Usage="Both" 
              VirtualRowCol="19,8" 
              PositionCursor="57" 
              Color="Red : 57 , Green : !57" 
              TabIndex="27"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DI4NB" runat="server" style="position: absolute; left: 289px; top: 432px; width: 28px"
              CssClass="DdsDecField"
              Length="3" 
              Decimals="0" 
              LeftPad="Zeroes" 
              Alias="#DI4NB" 
              Usage="Both" 
              VirtualRowCol="19,29" 
              PositionCursor="58" 
              Color="Red : 58 , Green : !58" 
              EditCode="4" 
              TabIndex="28"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGKVA" runat="server" style="position: absolute; left: 325px; top: 432px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGKVA" 
              Usage="Both" 
              VirtualRowCol="19,33" 
              PositionCursor="59" 
              Color="Red : 59 , Green : !59" 
              EditCode="4" 
              TabIndex="29"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGNVA" runat="server" style="position: absolute; left: 424px; top: 432px; width: 82px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              LeftPad="Blanks" 
              Alias="#DGNVA" 
              Usage="Both" 
              VirtualRowCol="19,44" 
              PositionCursor="60" 
              Color="Red : 60 , Green : !60" 
              EditCode="4" 
              TabIndex="30"  />
            <mdf:DdsDecField id="_lb_RCDDTL1__lb_DGQVA" runat="server" style="position: absolute; left: 523px; top: 432px; width: 109px"
              CssClass="DdsDecField"
              Length="9" 
              Decimals="2" 
              Alias="#DGQVA" 
              Usage="OutputOnly" 
              VirtualRowCol="19,55" 
              EditCode="J" 
 />
          </mdf:DdsRecord >
          <mdf:DdsRecord id="_lb_CMDTXT1" runat="server" 
            style="position: relative; width: 342px; height: 24px" 
            Alias="#CMDTXT1"
            CssClass="DdsRecord"
          >&nbsp;
          <%--  Command key text                                                                --%>
          <%-- =========================================================================        --%>
            <mdf:DdsConstant id="DdsConstant19" runat="server" 
              style="position: absolute; left: 19px; top: 3px;"
              Text="F3=Exit  F4=Prompt  F9=Get Customer" 
              CssClass="DdsConstant"
 />
          </mdf:DdsRecord >
          <mdf:DdsSubfileControl id="_lb_MSGCTL" runat="server" 
            style="position: relative; width: 9px; height: 48px" 
            Alias="#MSGCTL"
            CssClass="DdsRecord"
            ProgramQ="##PGM" 
            DisplayFields="*True" 
            DisplayRecords="*True" 
            InitializeRecords="*True" 
            SubfilePage="1" 
            SubfileSize="3" 
            SubFileEnd="25 | !25"
            SubFileEndTextOn=""
            SubFileEndTextOff="+"
          >&nbsp;
          <%-- =========================================================================        --%>
          <mdf:DdsSubfile id="_lb_MSGRCD" runat="server" 
            style="position: absolute; left: 0px; top: 0px; width: 9px; height: 24px" 
            Alias="#MSGRCD"
            CssClass="DdsSubfileRecord"
            UseSubfilePaging="True" 
            RowsCssClasses="DefaultRow AlternateRow"
          >&nbsp;
          <%-- =========================================================================        --%>
            <mdf:DdsCharField id="_lb_MSGRCD_MSGKEY" runat="server" 
              style="position: absolute; left: 8px; top: 0px; width: 600px"
              Alias="MSGKEY"
              Length="76" 
              Usage="OutputOnly" 
              CssClass="DdsSflMsgField" />
          </mdf:DdsSubfile >
          </mdf:DdsSubfileControl >

        </div>
    </asp:Content>

    <asp:Content ID="FileContent3" runat="server" ContentPlaceHolderID="MsgPH">
        <mdf:DdsMessagePanel ID="DdsMessagePanel1" Style="position: relative" runat="server" Height="64px"></mdf:DdsMessagePanel>
    </asp:Content>

    <asp:Content ContentPlaceHolderID="PageScriptPH" runat="server" >
    </asp:Content>
